name: CD to GitHub Pages
run-name: ${{ github.actor }} is deploying to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🛫 CD was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Job is running on a ${{ runner.os }}"
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: "npm"
      - run: npm i
      - run: npm run build
      - run: git subtree push --prefix dist origin gh-pages
      - run: echo "🛬 Job finished with the status ${{ job.status }}."
